# Generated by Django 5.0.6 on 2024-06-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='jop_title',
        ),
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_published_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
