# Generated by Django 5.0.6 on 2024-06-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_title_job_jop_title_job_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_experience',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='job_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='job_vacancy',
            field=models.IntegerField(default=1),
        ),
    ]
