# Generated by Django 5.0.6 on 2024-06-15 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_catogry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job.category'),
            preserve_default=False,
        ),
    ]
